package opnsense

import (
	"context"
	"encoding/json"
	"fmt"
)

// Endpoint is the source or destination of a NAT rule.
type Endpoint struct {
	Network string `json:"network,omitempty"`
	Port    string `json:"port,omitempty"`
}

// NATRule is a destination NAT (port forward) rule
// (Firewall > NAT > Destination NAT), available since OPNsense 26.1.
type NATRule struct {
	UUID        string   `json:"uuid,omitempty"`
	Disabled    string   `json:"disabled"`
	Interface   string   `json:"interface"`
	IPProtocol  string   `json:"ipprotocol"`
	Protocol    string   `json:"protocol"`
	Source      Endpoint `json:"source"`
	Destination Endpoint `json:"destination"`
	Target      string   `json:"target"`
	LocalPort   string   `json:"local-port"`
	// Pass controls the associated filter rule: "pass" lets matching traffic
	// through, "rule" registers a separate rule, "" means manual.
	Pass        string `json:"pass"`
	Description string `json:"descr"`
}

// natRuleRow is a row as returned by search_rule, where nested fields are
// flattened into dotted keys.
type natRuleRow struct {
	UUID               string `json:"uuid"`
	Disabled           string `json:"disabled"`
	Interface          string `json:"interface"`
	IPProtocol         string `json:"ipprotocol"`
	Protocol           string `json:"protocol"`
	SourceNetwork      string `json:"source.network"`
	SourcePort         string `json:"source.port"`
	DestinationNetwork string `json:"destination.network"`
	DestinationPort    string `json:"destination.port"`
	Target             string `json:"target"`
	LocalPort          string `json:"local-port"`
	Pass               string `json:"pass"`
	Description        string `json:"descr"`
	IsAutomatic        bool   `json:"is_automatic"`
}

func (r natRuleRow) rule() NATRule {
	return NATRule{
		UUID:        r.UUID,
		Disabled:    r.Disabled,
		Interface:   r.Interface,
		IPProtocol:  r.IPProtocol,
		Protocol:    r.Protocol,
		Source:      Endpoint{Network: r.SourceNetwork, Port: r.SourcePort},
		Destination: Endpoint{Network: r.DestinationNetwork, Port: r.DestinationPort},
		Target:      r.Target,
		LocalPort:   r.LocalPort,
		Pass:        r.Pass,
		Description: r.Description,
	}
}

// SearchNATRules returns all user-defined destination NAT rules. Automatic
// rules generated by OPNsense itself are omitted.
func (c *Client) SearchNATRules(ctx context.Context) ([]NATRule, error) {
	var res struct {
		Rows []json.RawMessage `json:"rows"`
	}
	if err := c.post(ctx, "/api/firewall/d_nat/search_rule", searchRequest, &res); err != nil {
		return nil, fmt.Errorf("search NAT rules: %w", err)
	}
	rules := make([]NATRule, 0, len(res.Rows))
	for _, raw := range res.Rows {
		var row natRuleRow
		if err := json.Unmarshal(raw, &row); err != nil {
			// Automatic rows may carry differently typed fields; they are never ours.
			continue
		}
		if row.IsAutomatic {
			continue
		}
		rules = append(rules, row.rule())
	}
	return rules, nil
}

// AddNATRule creates a destination NAT rule and returns its UUID.
func (c *Client) AddNATRule(ctx context.Context, r NATRule) (string, error) {
	r.UUID = ""
	uuid, err := c.mutate(ctx, "/api/firewall/d_nat/add_rule", map[string]any{"rule": r})
	if err != nil {
		return "", fmt.Errorf("add NAT rule %q: %w", r.Description, err)
	}
	return uuid, nil
}

// DelNATRule deletes the destination NAT rule with the given UUID.
func (c *Client) DelNATRule(ctx context.Context, uuid string) error {
	if _, err := c.mutate(ctx, "/api/firewall/d_nat/del_rule/"+uuid, nil); err != nil {
		return fmt.Errorf("delete NAT rule %s: %w", uuid, err)
	}
	return nil
}

// ApplyFirewall reloads the firewall so NAT rule changes take effect.
func (c *Client) ApplyFirewall(ctx context.Context) error {
	if err := c.post(ctx, "/api/firewall/d_nat/apply", nil, nil); err != nil {
		return fmt.Errorf("apply firewall: %w", err)
	}
	return nil
}
